config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy] do
    collection do
      get :backdoor
      post :ready
    end
  end
  resource :home, only: [:show]

  root to: "home#show"

  resources :awssamplers, :only => %i[index] do
    collection do
      post :create_keypair
      get :delete_stack
      post :check_status
    end
    member do
      get :list_s3_buckets
    end
  end

  resources :teams, :only => %i[index new create edit update destroy] do
    collection do
      get :select_join
      get :export
      get :scoreboard
    end
    member do
      get :dashboard
      get :details
      post :kick
      post :quit
      post :request_join
      post :cancel_join_request
      post :accept_join_request
      post :deny_join_request
      post :promote
      post :ignore_joins
      post :watch_joins
    end
  end

  resources :users, :only => %i[edit update]

  resources :quests, :only => %i[index new create edit update destroy] do
    member do
      post :publish
      post :unpublish
      post :addprereq
      post :removeprereq
    end
  end

  resource :teamquest, only: [:show] do
    member do
      get :step
      post :answer
    end
  end

  resources :steps

  namespace :api do
    namespace :v1 do
      resources :api do
        collection do
          post :stack_complete
        end
      end
    end
  end
end

app/models/quest.rb
class Quest < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: {minimum: 5, maximum: 25}

  scope :published, -> { where(is_published: true) }

  scope :has_prereqs, -> { joins(:prereqs) }
  scope :has_no_prereqs, -> { where("quests.id NOT IN (?)", Quest.has_prereqs.select(:id)) }

  scope :prereq_of, -> (quest_id) { where("quests.id IN (?)", Quest.find(quest_id).prereqs.select(:required_quest_id)) }
  scope :not_prereq_of, ->(quest_id) { where("quests.id NOT IN (?)",
    Quest.prereq_of(quest_id).or(Quest.where(id: quest_id)).select(:id)) }

  has_many :steps, -> { order(step_number: :asc) }, :class_name => 'Step', dependent: :destroy, inverse_of: :quest
  has_many :prereqs, :class_name => 'Prereq', dependent: :destroy, inverse_of: :quest
  has_many :required_by_prereqs, :class_name => "Prereq", dependent: :destroy, inverse_of: :required_quest, :foreign_key => "required_quest_id"


  def total_score
    return 0 if steps.blank?
    steps.sum(:points)
  end

  def steps_up_to(step_number)
    steps.where("steps.step_number <= ?", step_number)
  end

  def last_step_number
    steps.maximum(:step_number)
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :ensure_admin
  before_action :set_quest, only: [:edit, :update, :destroy, :publish, :unpublish, :addprereq, :removeprereq]

  def addprereq
    Rails.logger.error "Inside adding prereq"
    required_quest_id = params[:required_quest_id]

    # Make sure we don't already have this prereq
    unless @quest.prereqs.where(required_quest_id: required_quest_id).present?
      # Make sure the prereq quest_id actually exists
      if Quest.where(id: required_quest_id).present?
        prereq = @quest.prereqs.build(required_quest_id: required_quest_id)
        prereq.save
      end
    end

    redirect_to edit_quest_path(@quest)
  end

  def removeprereq
    Rails.logger.error "Inside adding prereq"
    prereq_id = params[:prereq_id]

    prereq = Prereq.where(id: prereq_id)
    if prereq.present?
      prereq.first.destroy
    end

    redirect_to edit_quest_path(@quest)
  end

  def publish
    Teamquest.publish(@quest)

    @quest.is_published = true
    @quest.save
    redirect_to quests_path
  end

  def unpublish
    Teamquest.unpublish(@quest, true)

    @quest.is_published = false
    @quest.save
    redirect_to quests_path
  end

  # GET /quests
  def index
    @quests = Quest.all
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  # GET /quests/1/edit
  def edit
    @prereq_choices = Quest.not_prereq_of(@quest.id)
  end

  # POST /quests
  def create
    @quest = Quest.new(quest_params)
    @quest.is_published = false

    respond_to do |format|
      if @quest.save
        format.html { redirect_to quests_path, notice: 'Quest was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /quests/1
  def update
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to quests_path, notice: 'Quest was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /quests/1
  def destroy
    @quest.destroy
    respond_to do |format|
      format.html { redirect_to quests_url, notice: 'Quest was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = Quest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quest_params
      params.require(:quest).permit(:name)
    end
end

app/views/quests/_form.html.erb
<%= form_for(quest) do |f| %>
  <div class="col-6">
    <%= f.label :searchchurch, "Name", class: "font-weight-bold" %>
    <div class="input-group input-group-lg">
      <%= f.text_field :name, placeholder: " Type your Quest Name here ", class: 'form-control input-lg', id: "searchurch" %>

      <span class="input-group-btn">
        <%= f.submit 'Save', class: "btn btn-default btn-lg" %>
      </span>
    </div>
  </div>
  <br>
  <%= render 'shared/errors', record: quest %>

<% end %>

app/views/quests/_prereqs.html.erb
<h2>Pre-Requisite Quests</h2>

<table class="table table-hover table-striped table-nonfluid">
  <thead class="color-header">
    <tr>
      <th scope="col"><%= ' Required Quest ' %></th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @quest.prereqs.each do |prereq| %>
      <tr>
        <th scope="row"><%= prereq.required_quest.name %></th>

        <td itemscope><%= link_to 'Remove', removeprereq_quest_path(@quest, prereq_id: prereq.id), method: :post, :title => 'Remove ' + prereq.required_quest.name, data: { confirm: 'Remove this prereq?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_tag(addprereq_quest_path(@quest), :method => "post", id: "addprereq-form") do %>
  <%= select_tag :required_quest_id, options_from_collection_for_select(@prereq_choices, "id", "name"), {:class => 'col-md-8'} %>
  <%= hidden_field_tag :quest_id, @quest.id %>
  <%= submit_tag "Add", :name => nil, class: 'col-md-2' %>
<% end %>

app/views/quests/edit.html.erb
<%= render 'form', quest: @quest %>
<br><br>

<div class="row">
    <div class="col-md-6"><%= render 'steps/index' %></div>
    <div class="col-md-6"><%= render 'prereqs' %></div>
</div>
<br><br>
<% if @quest.steps.present? %>
  <% if @quest.is_published %>
    <%= link_to 'Unpublish', unpublish_quest_path(@quest), method: :post, :class => 'btn btn-large btn-primary' %></td>
  <% else %>
    <%= link_to 'Publish', publish_quest_path(@quest), method: :post, :class => 'btn btn-large btn-primary' %></td>
  <% end %>
<% end %>
<%= link_to 'Quest List', quests_path, :class => 'btn btn-large btn-primary' %>

app/views/quests/index.html.erb
<h1>Quests</h1>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @quests.each do |quest| %>
      <tr>
        <td><%= quest.name %></td>
        <td><%= link_to 'Edit', edit_quest_path(quest), class: 'p-2' %></td>
        <td><%= link_to 'Delete', quest, method: :delete, data: { confirm: 'Are you sure?' }, class: 'p-2' %></td>
        <td>
          <% if quest.steps %>
            <% if quest.is_published %>
              <%= link_to 'Unpublish', unpublish_quest_path(quest), method: :post, class: 'p-2' %></td>
            <% else %>
              <%= link_to 'Publish', publish_quest_path(quest), method: :post, class: 'p-2' %></td>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quest', new_quest_path, :class => 'btn btn-large btn-primary' %>

app/views/quests/new.html.erb
<%= render 'form', quest: @quest %>

<%= link_to 'Cancel', quests_path, :class => 'btn btn-large btn-primary' %>