config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy] do
    collection do
      get :backdoor
      post :ready
    end
  end
  resource :home, only: [:show]

  root to: "home#show"

  resources :awssamplers, :only => %i[index] do
    collection do
      post :create_keypair
      get :delete_stack
      post :check_status
    end
    member do
      get :list_s3_buckets
    end
  end

  resources :teams, :only => %i[index new create edit update destroy] do
    collection do
      get :select_join
      get :export
      get :scoreboard
    end
    member do
      get :dashboard
      get :details
      post :kick
      post :quit
      post :request_join
      post :cancel_join_request
      post :accept_join_request
      post :deny_join_request
      post :promote
      post :ignore_joins
      post :watch_joins
    end
  end

  resources :users, :only => %i[edit update]

  resources :quests, :only => %i[index new create edit update destroy] do
    member do
      post :publish
      post :unpublish
      post :addprereq
      post :removeprereq
    end
  end

  resource :teamquest, only: [:show] do
    member do
      get :step
      post :answer
    end
  end

  resources :steps

  namespace :api do
    namespace :v1 do
      resources :api do
        collection do
          post :stack_complete
        end
      end
    end
  end
end

app/controllers/Awssamplers_controller.rb
require 'AwsWrapper'
require 'AwsKeyPairs'
require 'AwsCloudFormation'

class AwssamplersController < ApplicationController
  before_action :ensure_admin
  before_action :set_team, only: %i[create_keypair check_status delete_stack]

  def index

  end

  def list_s3_buckets
    aws = AwsWrapper.new
    @buckets = aws.list_all_s3_buckets
  end

  # http://localhost:3000/awssampler/create_keypair?team_id=9
  def create_keypair
    key_name = 'elis-example-team-' + @team.id.to_s
    bucket_name = key_name
    key_file_name = "your_ssh_key.pem"

    # Make a key pair
    aws = AwsKeyPairs.new
    key_pair = aws.create_key_pair(key_name)

    # Only save the data if the key pair was created.
    # If it already existed, then it's already in S3.
    s3 = AwsWrapper.new
    if key_pair.present?
      # Store into S3
      s3.create_bucket(bucket_name)
      s3.write_to_s3(bucket_name, key_file_name, key_pair.key_material)
    end

    @url = s3.signed_url(bucket_name, key_file_name)

    cf = AwsCloudFormation.new
    stack_name = cf.team_created(@team.id, key_name)

    @team.keypair_name = key_name
    @team.keypair_filename = key_file_name
    @team.bucket_name = bucket_name
    @team.stack_name = stack_name
    @team.save

    @status = "Never checked"
  end

  def check_status
    @url = params['url']

    cf = AwsCloudFormation.new
    @status = cf.stack_status(@team.stack_name)

    @output = nil
    if @status == 'CREATE_COMPLETE'
      outputs = cf.stack_outputs(@team.stack_name)
      @output = cf.parse_output(outputs, "URL")
    end

    render 'create_keypair'
  end

  def delete_stack
    cf = AwsCloudFormation.new
    cf.delete_stack(@team.stack_name)
    @status = cf.stack_status(@team.stack_name)
    @url = nil
    @output = nil
    render 'create_keypair'
  end

  private

  def set_team
    team = params['team_id']
    return redirect_to root_path if team.blank?
    teams = Team.where(id: team)
    return redirect_to root_path unless teams.present?
    @team = teams.first
    true
  end
end

app/views/awssamplers/create_keypair.html.erb
Use this URL to download your SSH Key Pair.
<br>
Remember, this is a secret used by your team to access your UNIX jumpbox.
<br>
If anyone else gets this key pair, they can access your jumpbox, too!
<br>
<strong>Keep it safe!</strong>
<br><br>
This URL link will expire in <strong>10 minutes</strong>.
<br><br>

<%= link_to "Download Your Key Pair", @url, :target => "_blank", :class => 'btn btn-large btn-success' %>


<br><br>
We are preparing your AWS account resources.  This will take a few minutes.
<br>
Once your resources are ready, you can follow
<%= link_to " these instructions ", 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html', :target => "_blank" %>
to connect to your AWS development box.

<%= form_tag(check_status_awssamplers_path, :method => "post", id: "checkstatus-form") do %>
  <div class="input-group col-md-4">
    <%= text_field_tag :status, @status, disabled: true, :class => 'form-control' %>
    <%= hidden_field_tag :url, @url %>
    <%= hidden_field_tag :team_id, @team.id %>
    <span class="input-group-btn">
      <%= submit_tag "Check Status", :name => nil, class: 'btn btn-success' %>
    </span>
  </div>
<% end %>

<% if @output.present? %>
  <%= 'Your Development box is: ' + @output.to_s %>
  <br>
  <%= link_to 'Delete AWS Resources', delete_stack_awssamplers_path(team_id: @team.id), class: "btn btn-large btn-warning" %>
<% end %>

app/views/awssamplers/index.html.erb
<h2>Test all your AWS connections</h2>
<br><br>

<%= form_tag(create_keypair_awssamplers_path, :method => "post", id: "create-keypair-form") do %>
  <div class="input-group col-md-4">
    <%= select_tag :team_id, options_from_collection_for_select(Team.all, "id", "name"), {:class => 'form-control'} %>
    <span class="input-group-btn">
      <%= submit_tag "Create Team Stack", :name => nil, class: 'btn btn-success' %>
    </span>
  </div>
<% end %>

app/views/awssamplers/list_s3_buckets.html.erb
<h1>S3 Buckets</h1>

<table class="table table-hover table-striped table-nonfluid">
  <thead class="color-header">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Creation Date</th>
    </tr>
  </thead>

  <tbody>
    <% @buckets.each do |bucket| %>
      <tr >
        <th scope="row"><%= bucket.name %></th>
        <td><%= bucket.creation_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>