config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy] do
    collection do
      get :backdoor
      post :ready
    end
  end
  resource :home, only: [:show]

  root to: "home#show"

  resources :awssamplers, :only => %i[index] do
    collection do
      post :create_keypair
      get :delete_stack
      post :check_status
    end
    member do
      get :list_s3_buckets
    end
  end

  resources :teams, :only => %i[index new create edit update destroy] do
    collection do
      get :select_join
      get :export
      get :scoreboard
    end
    member do
      get :dashboard
      get :details
      post :kick
      post :quit
      post :request_join
      post :cancel_join_request
      post :accept_join_request
      post :deny_join_request
      post :promote
      post :ignore_joins
      post :watch_joins
    end
  end

  resources :users, :only => %i[edit update]

  resources :quests, :only => %i[index new create edit update destroy] do
    member do
      post :publish
      post :unpublish
      post :addprereq
      post :removeprereq
    end
  end

  resource :teamquest, only: [:show] do
    member do
      get :step
      post :answer
    end
  end

  resources :steps

  namespace :api do
    namespace :v1 do
      resources :api do
        collection do
          post :stack_complete
        end
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    return redirect_to(dashboard_team_path(current_user.team)) if current_user && current_user.team.present?
  end
end

app/views/home/_admin_dash.html.erb
<div class="row">
  <div class="col-3"></div>
  <%= link_to "Manage Teams", teams_path, class: "btn btn-large btn-warning m-2 col-2" %>
  <%= link_to "Manage Quests", quests_path, class: "btn btn-large btn-warning m-2 col-2" %>
  <%= link_to "Test AWS", awssamplers_path, class: "btn btn-large btn-warning m-2 col-2" %>
</div>

app/views/home/_login_splash.html.erb
<div class="p-3">
  <div class="text-center" style="font-size: 60px;">
    VOYAGE
  </div>
  <br>

  <div class="text-center">
    <p>Begin your journey through cyber security</p>
  </div>
</div>

app/views/home/_team_dashboard.html.erb
team_dashboard

<%= current_user.team.name %>

app/views/home/_team_selection.html.erb
<h3 class="text-center">
  <strong>Voyage is best played as part of a team.</strong>
</h3>

<div class="row">
  <div class="col-4"></div>
  <%= link_to "Create a new team", new_team_path, class: "btn btn-large btn-warning col-2 m-2" %>
  <%= link_to "Join an existing team", select_join_teams_path, class: "btn btn-large btn-warning m-2 col-2" %>
</div>

app/views/home/show.html.erb
<% if current_user %>
  <% if current_user.is_admin %>
    <%= render :partial => 'admin_dash' %>
  <% elsif current_user.team.nil? %>
    <%= render :partial => 'team_selection' %>
  <% else %>
    <%= render :partial => 'team_dashboard' %>
  <% end %>
<% else %>
  <%= render :partial => 'login_splash' %>
<% end %>